name: Build and Release

on: [push, pull_request]

jobs:
  build:
    name: Run builder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download EB4J-tools
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: eb4j/eb4j-tools
        tag: 'v2.2.3'
        path: download
        file: eb-linux-x86-64-2.2.3.zip
    - name: extract eb4j-tools
      run: |
        mkdir bin
        cd bin
        unzip ../download/eb-linux-x86-64-2.2.3.zip
        chmod +x eb
    - name: Build furoku
      run: |
        mkdir dist
        for src in genius.yml genius43.yml kojien.yml unno5.yml unno602.yml
        do
           target=`basename ${src} .yml`
           mkdir ${target}
           bin/eb appendix -o ${target} ${src}
           zip -r dist/${target}.zip ${target}
        done
    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: release-files
        path: dist/
    - name: Update Tag
      if: github.ref == 'refs/heads/main'
      run: |
        git tag --force continuous-build ${GITHUB_SHA}
        git push --force --tags
    - name: Update Continuous Build Release
      if: github.ref == 'refs/heads/main'
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/genius.zip dist/genius43.zip dist/kojien.zip dist/unno5.zip dist/unno602.zip
        release: Continuous Build
        tag: continuous-build

  release:
    name: publish on github release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: release-files
        path: distributions
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      id: create_release
      with:
        title: Release v${{ steps.get_version.outputs.VERSION }}
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: false
        prerelease: false
        files: |
          distributions/*.zip
